namespace Cafe
{
    partial class POSForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(POSForm));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.flowLayoutPanelProducts = new System.Windows.Forms.FlowLayoutPanel();
            this.DgvCheckout = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.lblGrandTotal = new System.Windows.Forms.Label();
            this.lblGrand = new System.Windows.Forms.Label();
            this.printDocument1 = new System.Drawing.Printing.PrintDocument();
            this.bunifuShadowPanel2 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.BtnCheckout = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.BtnClose = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.Btnback = new Bunifu.UI.WinForms.BunifuPictureBox();
            this.POSSearch = new Bunifu.UI.WinForms.BunifuTextBox();
            this.BtnAllmenu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.BtnCoffee = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Catejuice = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CateKhDrink = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CateFood = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.CateSmoothie = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            ((System.ComponentModel.ISupportInitialize)(this.DgvCheckout)).BeginInit();
            this.bunifuShadowPanel2.SuspendLayout();
            this.bunifuGradientPanel1.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.BtnClose)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.Btnback)).BeginInit();
            this.SuspendLayout();
            // 
            // flowLayoutPanelProducts
            // 
            this.flowLayoutPanelProducts.Anchor = System.Windows.Forms.AnchorStyles.None;
            this.flowLayoutPanelProducts.AutoScroll = true;
            this.flowLayoutPanelProducts.Location = new System.Drawing.Point(0, 159);
            this.flowLayoutPanelProducts.Name = "flowLayoutPanelProducts";
            this.flowLayoutPanelProducts.Size = new System.Drawing.Size(693, 646);
            this.flowLayoutPanelProducts.TabIndex = 1;
            // 
            // DgvCheckout
            // 
            this.DgvCheckout.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(217)))), ((int)(((byte)(198)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.DgvCheckout.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.DgvCheckout.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.DgvCheckout.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.DgvCheckout.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.DgvCheckout.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.Chocolate;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(84)))), ((int)(((byte)(24)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.DgvCheckout.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.DgvCheckout.ColumnHeadersHeight = 40;
            this.DgvCheckout.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(243)))), ((int)(((byte)(217)))), ((int)(((byte)(198)))));
            this.DgvCheckout.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DgvCheckout.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DgvCheckout.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(165)))), ((int)(((byte)(120)))));
            this.DgvCheckout.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.DgvCheckout.CurrentTheme.BackColor = System.Drawing.Color.Chocolate;
            this.DgvCheckout.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(210)))), ((int)(((byte)(187)))));
            this.DgvCheckout.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.Chocolate;
            this.DgvCheckout.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.DgvCheckout.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.DgvCheckout.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(84)))), ((int)(((byte)(24)))));
            this.DgvCheckout.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.DgvCheckout.CurrentTheme.Name = null;
            this.DgvCheckout.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(225)))), ((int)(((byte)(210)))));
            this.DgvCheckout.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.DgvCheckout.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.DgvCheckout.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(165)))), ((int)(((byte)(120)))));
            this.DgvCheckout.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(246)))), ((int)(((byte)(225)))), ((int)(((byte)(210)))));
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(165)))), ((int)(((byte)(120)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.DgvCheckout.DefaultCellStyle = dataGridViewCellStyle3;
            this.DgvCheckout.EnableHeadersVisualStyles = false;
            this.DgvCheckout.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(241)))), ((int)(((byte)(210)))), ((int)(((byte)(187)))));
            this.DgvCheckout.HeaderBackColor = System.Drawing.Color.Chocolate;
            this.DgvCheckout.HeaderBgColor = System.Drawing.Color.Empty;
            this.DgvCheckout.HeaderForeColor = System.Drawing.Color.White;
            this.DgvCheckout.Location = new System.Drawing.Point(3, 6);
            this.DgvCheckout.Name = "DgvCheckout";
            this.DgvCheckout.ReadOnly = true;
            this.DgvCheckout.RowHeadersVisible = false;
            this.DgvCheckout.RowHeadersWidth = 51;
            this.DgvCheckout.RowTemplate.Height = 40;
            this.DgvCheckout.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.DgvCheckout.Size = new System.Drawing.Size(778, 542);
            this.DgvCheckout.TabIndex = 2;
            this.DgvCheckout.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Chocolate;
            // 
            // lblGrandTotal
            // 
            this.lblGrandTotal.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.lblGrandTotal.AutoSize = true;
            this.lblGrandTotal.Font = new System.Drawing.Font("Poppins", 13.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblGrandTotal.Location = new System.Drawing.Point(201, 569);
            this.lblGrandTotal.Name = "lblGrandTotal";
            this.lblGrandTotal.Size = new System.Drawing.Size(86, 40);
            this.lblGrandTotal.TabIndex = 4;
            this.lblGrandTotal.Text = "label1";
            this.lblGrandTotal.Visible = false;
            // 
            // lblGrand
            // 
            this.lblGrand.AutoSize = true;
            this.lblGrand.Font = new System.Drawing.Font("Kantumruy Pro", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblGrand.ForeColor = System.Drawing.Color.Red;
            this.lblGrand.Location = new System.Drawing.Point(48, 567);
            this.lblGrand.Name = "lblGrand";
            this.lblGrand.Size = new System.Drawing.Size(97, 42);
            this.lblGrand.TabIndex = 4;
            this.lblGrand.Text = "សរុប​ : ";
            // 
            // bunifuShadowPanel2
            // 
            this.bunifuShadowPanel2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel2.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.BorderRadius = 1;
            this.bunifuShadowPanel2.BorderThickness = 1;
            this.bunifuShadowPanel2.Controls.Add(this.lblGrandTotal);
            this.bunifuShadowPanel2.Controls.Add(this.BtnCheckout);
            this.bunifuShadowPanel2.Controls.Add(this.lblGrand);
            this.bunifuShadowPanel2.Controls.Add(this.DgvCheckout);
            this.bunifuShadowPanel2.Dock = System.Windows.Forms.DockStyle.Right;
            this.bunifuShadowPanel2.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel2.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel2.Location = new System.Drawing.Point(699, 153);
            this.bunifuShadowPanel2.Name = "bunifuShadowPanel2";
            this.bunifuShadowPanel2.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel2.ShadowColor = System.Drawing.Color.DarkGray;
            this.bunifuShadowPanel2.ShadowDept = 2;
            this.bunifuShadowPanel2.ShadowDepth = 5;
            this.bunifuShadowPanel2.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel2.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel2.Size = new System.Drawing.Size(784, 652);
            this.bunifuShadowPanel2.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel2.TabIndex = 7;
            // 
            // BtnCheckout
            // 
            this.BtnCheckout.AllowAnimations = true;
            this.BtnCheckout.AllowMouseEffects = true;
            this.BtnCheckout.AllowToggling = false;
            this.BtnCheckout.AnimationSpeed = 200;
            this.BtnCheckout.AutoGenerateColors = false;
            this.BtnCheckout.AutoRoundBorders = false;
            this.BtnCheckout.AutoSizeLeftIcon = true;
            this.BtnCheckout.AutoSizeRightIcon = true;
            this.BtnCheckout.BackColor = System.Drawing.Color.Transparent;
            this.BtnCheckout.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(176)))), ((int)(((byte)(90)))));
            this.BtnCheckout.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCheckout.BackgroundImage")));
            this.BtnCheckout.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCheckout.ButtonText = "គិតលុយ";
            this.BtnCheckout.ButtonTextMarginLeft = 0;
            this.BtnCheckout.ColorContrastOnClick = 45;
            this.BtnCheckout.ColorContrastOnHover = 45;
            this.BtnCheckout.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.BtnCheckout.CustomizableEdges = borderEdges1;
            this.BtnCheckout.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCheckout.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCheckout.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCheckout.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCheckout.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCheckout.Font = new System.Drawing.Font("Kantumruy Pro", 16.2F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCheckout.ForeColor = System.Drawing.Color.White;
            this.BtnCheckout.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCheckout.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCheckout.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCheckout.IconMarginLeft = 11;
            this.BtnCheckout.IconPadding = 10;
            this.BtnCheckout.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCheckout.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCheckout.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCheckout.IconSize = 25;
            this.BtnCheckout.IdleBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(176)))), ((int)(((byte)(90)))));
            this.BtnCheckout.IdleBorderRadius = 20;
            this.BtnCheckout.IdleBorderThickness = 1;
            this.BtnCheckout.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(176)))), ((int)(((byte)(90)))));
            this.BtnCheckout.IdleIconLeftImage = null;
            this.BtnCheckout.IdleIconRightImage = null;
            this.BtnCheckout.IndicateFocus = false;
            this.BtnCheckout.Location = new System.Drawing.Point(291, 628);
            this.BtnCheckout.Name = "BtnCheckout";
            this.BtnCheckout.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCheckout.OnDisabledState.BorderRadius = 20;
            this.BtnCheckout.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCheckout.OnDisabledState.BorderThickness = 1;
            this.BtnCheckout.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCheckout.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCheckout.OnDisabledState.IconLeftImage = null;
            this.BtnCheckout.OnDisabledState.IconRightImage = null;
            this.BtnCheckout.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnCheckout.onHoverState.BorderRadius = 20;
            this.BtnCheckout.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCheckout.onHoverState.BorderThickness = 1;
            this.BtnCheckout.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnCheckout.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCheckout.onHoverState.IconLeftImage = null;
            this.BtnCheckout.onHoverState.IconRightImage = null;
            this.BtnCheckout.OnIdleState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(176)))), ((int)(((byte)(90)))));
            this.BtnCheckout.OnIdleState.BorderRadius = 20;
            this.BtnCheckout.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCheckout.OnIdleState.BorderThickness = 1;
            this.BtnCheckout.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(25)))), ((int)(((byte)(176)))), ((int)(((byte)(90)))));
            this.BtnCheckout.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnCheckout.OnIdleState.IconLeftImage = null;
            this.BtnCheckout.OnIdleState.IconRightImage = null;
            this.BtnCheckout.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCheckout.OnPressedState.BorderRadius = 20;
            this.BtnCheckout.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCheckout.OnPressedState.BorderThickness = 1;
            this.BtnCheckout.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCheckout.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCheckout.OnPressedState.IconLeftImage = null;
            this.BtnCheckout.OnPressedState.IconRightImage = null;
            this.BtnCheckout.Size = new System.Drawing.Size(179, 71);
            this.BtnCheckout.TabIndex = 5;
            this.BtnCheckout.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCheckout.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCheckout.TextMarginLeft = 0;
            this.BtnCheckout.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCheckout.UseDefaultRadiusAndThickness = true;
            this.BtnCheckout.Click += new System.EventHandler(this.BtnCheckout_Click);
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.BtnClose);
            this.bunifuGradientPanel1.Controls.Add(this.Btnback);
            this.bunifuGradientPanel1.Controls.Add(this.POSSearch);
            this.bunifuGradientPanel1.Controls.Add(this.BtnAllmenu);
            this.bunifuGradientPanel1.Controls.Add(this.BtnCoffee);
            this.bunifuGradientPanel1.Controls.Add(this.Catejuice);
            this.bunifuGradientPanel1.Controls.Add(this.CateKhDrink);
            this.bunifuGradientPanel1.Controls.Add(this.CateFood);
            this.bunifuGradientPanel1.Controls.Add(this.CateSmoothie);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(234)))), ((int)(((byte)(116)))), ((int)(((byte)(132)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(190)))), ((int)(((byte)(1)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(216)))), ((int)(((byte)(3)))), ((int)(((byte)(95)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(228)))), ((int)(((byte)(103)))), ((int)(((byte)(119)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(1483, 153);
            this.bunifuGradientPanel1.TabIndex = 3;
            // 
            // BtnClose
            // 
            this.BtnClose.AllowFocused = false;
            this.BtnClose.Anchor = System.Windows.Forms.AnchorStyles.Right;
            this.BtnClose.AutoSizeHeight = true;
            this.BtnClose.BorderRadius = 22;
            this.BtnClose.Cursor = System.Windows.Forms.Cursors.Hand;
            this.BtnClose.Image = global::Cafe.Properties.Resources.Close;
            this.BtnClose.IsCircle = true;
            this.BtnClose.Location = new System.Drawing.Point(1426, 5);
            this.BtnClose.Name = "BtnClose";
            this.BtnClose.Size = new System.Drawing.Size(45, 45);
            this.BtnClose.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.BtnClose.TabIndex = 3;
            this.BtnClose.TabStop = false;
            this.BtnClose.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.BtnClose.Click += new System.EventHandler(this.BtnClose_Click);
            // 
            // Btnback
            // 
            this.Btnback.AllowFocused = false;
            this.Btnback.Anchor = System.Windows.Forms.AnchorStyles.Left;
            this.Btnback.AutoSizeHeight = true;
            this.Btnback.BorderRadius = 22;
            this.Btnback.Cursor = System.Windows.Forms.Cursors.Hand;
            this.Btnback.Image = global::Cafe.Properties.Resources.back;
            this.Btnback.IsCircle = true;
            this.Btnback.Location = new System.Drawing.Point(12, 9);
            this.Btnback.Name = "Btnback";
            this.Btnback.Size = new System.Drawing.Size(44, 44);
            this.Btnback.SizeMode = System.Windows.Forms.PictureBoxSizeMode.Zoom;
            this.Btnback.TabIndex = 2;
            this.Btnback.TabStop = false;
            this.Btnback.Type = Bunifu.UI.WinForms.BunifuPictureBox.Types.Circle;
            this.Btnback.Click += new System.EventHandler(this.Btnback_Click);
            // 
            // POSSearch
            // 
            this.POSSearch.AcceptsReturn = false;
            this.POSSearch.AcceptsTab = false;
            this.POSSearch.AnimationSpeed = 200;
            this.POSSearch.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.POSSearch.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.POSSearch.BackColor = System.Drawing.Color.Transparent;
            this.POSSearch.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("POSSearch.BackgroundImage")));
            this.POSSearch.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.POSSearch.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.POSSearch.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.POSSearch.BorderColorIdle = System.Drawing.Color.Silver;
            this.POSSearch.BorderRadius = 25;
            this.POSSearch.BorderThickness = 1;
            this.POSSearch.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.POSSearch.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.POSSearch.DefaultFont = new System.Drawing.Font("Kantumruy Pro SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.POSSearch.DefaultText = "";
            this.POSSearch.FillColor = System.Drawing.Color.White;
            this.POSSearch.HideSelection = true;
            this.POSSearch.IconLeft = global::Cafe.Properties.Resources.Search;
            this.POSSearch.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.POSSearch.IconPadding = 6;
            this.POSSearch.IconRight = null;
            this.POSSearch.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.POSSearch.Lines = new string[0];
            this.POSSearch.Location = new System.Drawing.Point(99, 33);
            this.POSSearch.MaxLength = 32767;
            this.POSSearch.MinimumSize = new System.Drawing.Size(1, 1);
            this.POSSearch.Modified = false;
            this.POSSearch.Multiline = false;
            this.POSSearch.Name = "POSSearch";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.POSSearch.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.POSSearch.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.POSSearch.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.POSSearch.OnIdleState = stateProperties4;
            this.POSSearch.Padding = new System.Windows.Forms.Padding(3);
            this.POSSearch.PasswordChar = '\0';
            this.POSSearch.PlaceholderForeColor = System.Drawing.Color.DimGray;
            this.POSSearch.PlaceholderText = "Search";
            this.POSSearch.ReadOnly = false;
            this.POSSearch.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.POSSearch.SelectedText = "";
            this.POSSearch.SelectionLength = 0;
            this.POSSearch.SelectionStart = 0;
            this.POSSearch.ShortcutsEnabled = true;
            this.POSSearch.Size = new System.Drawing.Size(303, 44);
            this.POSSearch.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.POSSearch.TabIndex = 1;
            this.POSSearch.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.POSSearch.TextMarginBottom = 0;
            this.POSSearch.TextMarginLeft = 10;
            this.POSSearch.TextMarginTop = 0;
            this.POSSearch.TextPlaceholder = "Search";
            this.POSSearch.UseSystemPasswordChar = false;
            this.POSSearch.WordWrap = true;
            this.POSSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.POSSearch_KeyDown);
            // 
            // BtnAllmenu
            // 
            this.BtnAllmenu.AllowAnimations = true;
            this.BtnAllmenu.AllowMouseEffects = true;
            this.BtnAllmenu.AllowToggling = false;
            this.BtnAllmenu.AnimationSpeed = 200;
            this.BtnAllmenu.AutoGenerateColors = false;
            this.BtnAllmenu.AutoRoundBorders = false;
            this.BtnAllmenu.AutoSizeLeftIcon = true;
            this.BtnAllmenu.AutoSizeRightIcon = true;
            this.BtnAllmenu.BackColor = System.Drawing.Color.Transparent;
            this.BtnAllmenu.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.BtnAllmenu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnAllmenu.BackgroundImage")));
            this.BtnAllmenu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAllmenu.ButtonText = "ម៉ឺនុយទាំងអស់";
            this.BtnAllmenu.ButtonTextMarginLeft = 0;
            this.BtnAllmenu.ColorContrastOnClick = 45;
            this.BtnAllmenu.ColorContrastOnHover = 45;
            this.BtnAllmenu.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.BtnAllmenu.CustomizableEdges = borderEdges2;
            this.BtnAllmenu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnAllmenu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAllmenu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAllmenu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAllmenu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnAllmenu.Font = new System.Drawing.Font("Kantumruy Pro", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnAllmenu.ForeColor = System.Drawing.Color.White;
            this.BtnAllmenu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnAllmenu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAllmenu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnAllmenu.IconMarginLeft = 11;
            this.BtnAllmenu.IconPadding = 10;
            this.BtnAllmenu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnAllmenu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnAllmenu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnAllmenu.IconSize = 25;
            this.BtnAllmenu.IdleBorderColor = System.Drawing.Color.White;
            this.BtnAllmenu.IdleBorderRadius = 25;
            this.BtnAllmenu.IdleBorderThickness = 1;
            this.BtnAllmenu.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.BtnAllmenu.IdleIconLeftImage = null;
            this.BtnAllmenu.IdleIconRightImage = null;
            this.BtnAllmenu.IndicateFocus = false;
            this.BtnAllmenu.Location = new System.Drawing.Point(98, 93);
            this.BtnAllmenu.Name = "BtnAllmenu";
            this.BtnAllmenu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnAllmenu.OnDisabledState.BorderRadius = 25;
            this.BtnAllmenu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAllmenu.OnDisabledState.BorderThickness = 1;
            this.BtnAllmenu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnAllmenu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnAllmenu.OnDisabledState.IconLeftImage = null;
            this.BtnAllmenu.OnDisabledState.IconRightImage = null;
            this.BtnAllmenu.onHoverState.BorderColor = System.Drawing.Color.Blue;
            this.BtnAllmenu.onHoverState.BorderRadius = 25;
            this.BtnAllmenu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAllmenu.onHoverState.BorderThickness = 1;
            this.BtnAllmenu.onHoverState.FillColor = System.Drawing.Color.Blue;
            this.BtnAllmenu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnAllmenu.onHoverState.IconLeftImage = null;
            this.BtnAllmenu.onHoverState.IconRightImage = null;
            this.BtnAllmenu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.BtnAllmenu.OnIdleState.BorderRadius = 25;
            this.BtnAllmenu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAllmenu.OnIdleState.BorderThickness = 1;
            this.BtnAllmenu.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(192)))), ((int)(((byte)(192)))));
            this.BtnAllmenu.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.BtnAllmenu.OnIdleState.IconLeftImage = null;
            this.BtnAllmenu.OnIdleState.IconRightImage = null;
            this.BtnAllmenu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnAllmenu.OnPressedState.BorderRadius = 25;
            this.BtnAllmenu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnAllmenu.OnPressedState.BorderThickness = 1;
            this.BtnAllmenu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnAllmenu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnAllmenu.OnPressedState.IconLeftImage = null;
            this.BtnAllmenu.OnPressedState.IconRightImage = null;
            this.BtnAllmenu.Size = new System.Drawing.Size(130, 44);
            this.BtnAllmenu.TabIndex = 0;
            this.BtnAllmenu.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnAllmenu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnAllmenu.TextMarginLeft = 0;
            this.BtnAllmenu.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnAllmenu.UseDefaultRadiusAndThickness = true;
            this.BtnAllmenu.Click += new System.EventHandler(this.BtnAllmenu_Click);
            // 
            // BtnCoffee
            // 
            this.BtnCoffee.AllowAnimations = true;
            this.BtnCoffee.AllowMouseEffects = true;
            this.BtnCoffee.AllowToggling = false;
            this.BtnCoffee.AnimationSpeed = 200;
            this.BtnCoffee.AutoGenerateColors = false;
            this.BtnCoffee.AutoRoundBorders = false;
            this.BtnCoffee.AutoSizeLeftIcon = true;
            this.BtnCoffee.AutoSizeRightIcon = true;
            this.BtnCoffee.BackColor = System.Drawing.Color.Transparent;
            this.BtnCoffee.BackColor1 = System.Drawing.SystemColors.Control;
            this.BtnCoffee.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("BtnCoffee.BackgroundImage")));
            this.BtnCoffee.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCoffee.ButtonText = "ភេសជ្ជៈត្រជាក់";
            this.BtnCoffee.ButtonTextMarginLeft = 0;
            this.BtnCoffee.ColorContrastOnClick = 45;
            this.BtnCoffee.ColorContrastOnHover = 45;
            this.BtnCoffee.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.BtnCoffee.CustomizableEdges = borderEdges3;
            this.BtnCoffee.DialogResult = System.Windows.Forms.DialogResult.None;
            this.BtnCoffee.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCoffee.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCoffee.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCoffee.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.BtnCoffee.Font = new System.Drawing.Font("Kantumruy Pro", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.BtnCoffee.ForeColor = System.Drawing.Color.Black;
            this.BtnCoffee.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.BtnCoffee.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCoffee.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.BtnCoffee.IconMarginLeft = 11;
            this.BtnCoffee.IconPadding = 10;
            this.BtnCoffee.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.BtnCoffee.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.BtnCoffee.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.BtnCoffee.IconSize = 25;
            this.BtnCoffee.IdleBorderColor = System.Drawing.Color.DimGray;
            this.BtnCoffee.IdleBorderRadius = 25;
            this.BtnCoffee.IdleBorderThickness = 1;
            this.BtnCoffee.IdleFillColor = System.Drawing.SystemColors.Control;
            this.BtnCoffee.IdleIconLeftImage = null;
            this.BtnCoffee.IdleIconRightImage = null;
            this.BtnCoffee.IndicateFocus = false;
            this.BtnCoffee.Location = new System.Drawing.Point(259, 93);
            this.BtnCoffee.Name = "BtnCoffee";
            this.BtnCoffee.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.BtnCoffee.OnDisabledState.BorderRadius = 25;
            this.BtnCoffee.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCoffee.OnDisabledState.BorderThickness = 1;
            this.BtnCoffee.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.BtnCoffee.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.BtnCoffee.OnDisabledState.IconLeftImage = null;
            this.BtnCoffee.OnDisabledState.IconRightImage = null;
            this.BtnCoffee.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnCoffee.onHoverState.BorderRadius = 25;
            this.BtnCoffee.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCoffee.onHoverState.BorderThickness = 1;
            this.BtnCoffee.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.BtnCoffee.onHoverState.ForeColor = System.Drawing.Color.White;
            this.BtnCoffee.onHoverState.IconLeftImage = null;
            this.BtnCoffee.onHoverState.IconRightImage = null;
            this.BtnCoffee.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.BtnCoffee.OnIdleState.BorderRadius = 25;
            this.BtnCoffee.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCoffee.OnIdleState.BorderThickness = 1;
            this.BtnCoffee.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.BtnCoffee.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.BtnCoffee.OnIdleState.IconLeftImage = null;
            this.BtnCoffee.OnIdleState.IconRightImage = null;
            this.BtnCoffee.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCoffee.OnPressedState.BorderRadius = 25;
            this.BtnCoffee.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.BtnCoffee.OnPressedState.BorderThickness = 1;
            this.BtnCoffee.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.BtnCoffee.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.BtnCoffee.OnPressedState.IconLeftImage = null;
            this.BtnCoffee.OnPressedState.IconRightImage = null;
            this.BtnCoffee.Size = new System.Drawing.Size(126, 44);
            this.BtnCoffee.TabIndex = 0;
            this.BtnCoffee.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.BtnCoffee.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.BtnCoffee.TextMarginLeft = 0;
            this.BtnCoffee.TextPadding = new System.Windows.Forms.Padding(0);
            this.BtnCoffee.UseDefaultRadiusAndThickness = true;
            this.BtnCoffee.Click += new System.EventHandler(this.BtnCoffee_Click);
            // 
            // Catejuice
            // 
            this.Catejuice.AllowAnimations = true;
            this.Catejuice.AllowMouseEffects = true;
            this.Catejuice.AllowToggling = false;
            this.Catejuice.AnimationSpeed = 200;
            this.Catejuice.AutoGenerateColors = false;
            this.Catejuice.AutoRoundBorders = false;
            this.Catejuice.AutoSizeLeftIcon = true;
            this.Catejuice.AutoSizeRightIcon = true;
            this.Catejuice.BackColor = System.Drawing.Color.Transparent;
            this.Catejuice.BackColor1 = System.Drawing.SystemColors.Control;
            this.Catejuice.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Catejuice.BackgroundImage")));
            this.Catejuice.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Catejuice.ButtonText = "ទឹកក្រូច";
            this.Catejuice.ButtonTextMarginLeft = 0;
            this.Catejuice.ColorContrastOnClick = 45;
            this.Catejuice.ColorContrastOnHover = 45;
            this.Catejuice.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Catejuice.CustomizableEdges = borderEdges4;
            this.Catejuice.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Catejuice.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Catejuice.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Catejuice.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Catejuice.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Catejuice.Font = new System.Drawing.Font("Kantumruy Pro", 12F, System.Drawing.FontStyle.Bold);
            this.Catejuice.ForeColor = System.Drawing.Color.Black;
            this.Catejuice.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Catejuice.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Catejuice.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Catejuice.IconMarginLeft = 11;
            this.Catejuice.IconPadding = 10;
            this.Catejuice.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Catejuice.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Catejuice.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Catejuice.IconSize = 25;
            this.Catejuice.IdleBorderColor = System.Drawing.Color.DimGray;
            this.Catejuice.IdleBorderRadius = 25;
            this.Catejuice.IdleBorderThickness = 1;
            this.Catejuice.IdleFillColor = System.Drawing.SystemColors.Control;
            this.Catejuice.IdleIconLeftImage = null;
            this.Catejuice.IdleIconRightImage = null;
            this.Catejuice.IndicateFocus = false;
            this.Catejuice.Location = new System.Drawing.Point(941, 93);
            this.Catejuice.Name = "Catejuice";
            this.Catejuice.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Catejuice.OnDisabledState.BorderRadius = 25;
            this.Catejuice.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Catejuice.OnDisabledState.BorderThickness = 1;
            this.Catejuice.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Catejuice.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Catejuice.OnDisabledState.IconLeftImage = null;
            this.Catejuice.OnDisabledState.IconRightImage = null;
            this.Catejuice.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Catejuice.onHoverState.BorderRadius = 25;
            this.Catejuice.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Catejuice.onHoverState.BorderThickness = 1;
            this.Catejuice.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Catejuice.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Catejuice.onHoverState.IconLeftImage = null;
            this.Catejuice.onHoverState.IconRightImage = null;
            this.Catejuice.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.Catejuice.OnIdleState.BorderRadius = 25;
            this.Catejuice.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Catejuice.OnIdleState.BorderThickness = 1;
            this.Catejuice.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.Catejuice.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.Catejuice.OnIdleState.IconLeftImage = null;
            this.Catejuice.OnIdleState.IconRightImage = null;
            this.Catejuice.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Catejuice.OnPressedState.BorderRadius = 25;
            this.Catejuice.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Catejuice.OnPressedState.BorderThickness = 1;
            this.Catejuice.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Catejuice.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Catejuice.OnPressedState.IconLeftImage = null;
            this.Catejuice.OnPressedState.IconRightImage = null;
            this.Catejuice.Size = new System.Drawing.Size(94, 44);
            this.Catejuice.TabIndex = 0;
            this.Catejuice.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Catejuice.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Catejuice.TextMarginLeft = 0;
            this.Catejuice.TextPadding = new System.Windows.Forms.Padding(0);
            this.Catejuice.UseDefaultRadiusAndThickness = true;
            this.Catejuice.Click += new System.EventHandler(this.Catejuice_Click);
            // 
            // CateKhDrink
            // 
            this.CateKhDrink.AllowAnimations = true;
            this.CateKhDrink.AllowMouseEffects = true;
            this.CateKhDrink.AllowToggling = false;
            this.CateKhDrink.AnimationSpeed = 200;
            this.CateKhDrink.AutoGenerateColors = false;
            this.CateKhDrink.AutoRoundBorders = false;
            this.CateKhDrink.AutoSizeLeftIcon = true;
            this.CateKhDrink.AutoSizeRightIcon = true;
            this.CateKhDrink.BackColor = System.Drawing.Color.Transparent;
            this.CateKhDrink.BackColor1 = System.Drawing.SystemColors.Control;
            this.CateKhDrink.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CateKhDrink.BackgroundImage")));
            this.CateKhDrink.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateKhDrink.ButtonText = "ភេសជ្ជៈបែបខ្មែរ";
            this.CateKhDrink.ButtonTextMarginLeft = 0;
            this.CateKhDrink.ColorContrastOnClick = 45;
            this.CateKhDrink.ColorContrastOnHover = 45;
            this.CateKhDrink.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.CateKhDrink.CustomizableEdges = borderEdges5;
            this.CateKhDrink.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CateKhDrink.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CateKhDrink.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CateKhDrink.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CateKhDrink.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CateKhDrink.Font = new System.Drawing.Font("Kantumruy Pro", 12F, System.Drawing.FontStyle.Bold);
            this.CateKhDrink.ForeColor = System.Drawing.Color.Black;
            this.CateKhDrink.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CateKhDrink.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CateKhDrink.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CateKhDrink.IconMarginLeft = 11;
            this.CateKhDrink.IconPadding = 10;
            this.CateKhDrink.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CateKhDrink.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CateKhDrink.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CateKhDrink.IconSize = 25;
            this.CateKhDrink.IdleBorderColor = System.Drawing.Color.DimGray;
            this.CateKhDrink.IdleBorderRadius = 25;
            this.CateKhDrink.IdleBorderThickness = 1;
            this.CateKhDrink.IdleFillColor = System.Drawing.SystemColors.Control;
            this.CateKhDrink.IdleIconLeftImage = null;
            this.CateKhDrink.IdleIconRightImage = null;
            this.CateKhDrink.IndicateFocus = false;
            this.CateKhDrink.Location = new System.Drawing.Point(754, 93);
            this.CateKhDrink.Name = "CateKhDrink";
            this.CateKhDrink.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CateKhDrink.OnDisabledState.BorderRadius = 25;
            this.CateKhDrink.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateKhDrink.OnDisabledState.BorderThickness = 1;
            this.CateKhDrink.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CateKhDrink.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CateKhDrink.OnDisabledState.IconLeftImage = null;
            this.CateKhDrink.OnDisabledState.IconRightImage = null;
            this.CateKhDrink.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CateKhDrink.onHoverState.BorderRadius = 25;
            this.CateKhDrink.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateKhDrink.onHoverState.BorderThickness = 1;
            this.CateKhDrink.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CateKhDrink.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CateKhDrink.onHoverState.IconLeftImage = null;
            this.CateKhDrink.onHoverState.IconRightImage = null;
            this.CateKhDrink.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.CateKhDrink.OnIdleState.BorderRadius = 25;
            this.CateKhDrink.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateKhDrink.OnIdleState.BorderThickness = 1;
            this.CateKhDrink.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.CateKhDrink.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.CateKhDrink.OnIdleState.IconLeftImage = null;
            this.CateKhDrink.OnIdleState.IconRightImage = null;
            this.CateKhDrink.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CateKhDrink.OnPressedState.BorderRadius = 25;
            this.CateKhDrink.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateKhDrink.OnPressedState.BorderThickness = 1;
            this.CateKhDrink.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CateKhDrink.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CateKhDrink.OnPressedState.IconLeftImage = null;
            this.CateKhDrink.OnPressedState.IconRightImage = null;
            this.CateKhDrink.Size = new System.Drawing.Size(147, 44);
            this.CateKhDrink.TabIndex = 0;
            this.CateKhDrink.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CateKhDrink.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CateKhDrink.TextMarginLeft = 0;
            this.CateKhDrink.TextPadding = new System.Windows.Forms.Padding(0);
            this.CateKhDrink.UseDefaultRadiusAndThickness = true;
            this.CateKhDrink.Click += new System.EventHandler(this.CateKhDrink_Click);
            // 
            // CateFood
            // 
            this.CateFood.AllowAnimations = true;
            this.CateFood.AllowMouseEffects = true;
            this.CateFood.AllowToggling = false;
            this.CateFood.AnimationSpeed = 200;
            this.CateFood.AutoGenerateColors = false;
            this.CateFood.AutoRoundBorders = false;
            this.CateFood.AutoSizeLeftIcon = true;
            this.CateFood.AutoSizeRightIcon = true;
            this.CateFood.BackColor = System.Drawing.Color.Transparent;
            this.CateFood.BackColor1 = System.Drawing.SystemColors.Control;
            this.CateFood.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CateFood.BackgroundImage")));
            this.CateFood.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateFood.ButtonText = "អាហារ";
            this.CateFood.ButtonTextMarginLeft = 0;
            this.CateFood.ColorContrastOnClick = 45;
            this.CateFood.ColorContrastOnHover = 45;
            this.CateFood.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.CateFood.CustomizableEdges = borderEdges6;
            this.CateFood.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CateFood.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CateFood.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CateFood.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CateFood.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CateFood.Font = new System.Drawing.Font("Kantumruy Pro", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.CateFood.ForeColor = System.Drawing.Color.Black;
            this.CateFood.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CateFood.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CateFood.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CateFood.IconMarginLeft = 11;
            this.CateFood.IconPadding = 10;
            this.CateFood.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CateFood.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CateFood.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CateFood.IconSize = 25;
            this.CateFood.IdleBorderColor = System.Drawing.Color.DimGray;
            this.CateFood.IdleBorderRadius = 25;
            this.CateFood.IdleBorderThickness = 1;
            this.CateFood.IdleFillColor = System.Drawing.SystemColors.Control;
            this.CateFood.IdleIconLeftImage = null;
            this.CateFood.IdleIconRightImage = null;
            this.CateFood.IndicateFocus = false;
            this.CateFood.Location = new System.Drawing.Point(420, 93);
            this.CateFood.Name = "CateFood";
            this.CateFood.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CateFood.OnDisabledState.BorderRadius = 25;
            this.CateFood.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateFood.OnDisabledState.BorderThickness = 1;
            this.CateFood.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CateFood.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CateFood.OnDisabledState.IconLeftImage = null;
            this.CateFood.OnDisabledState.IconRightImage = null;
            this.CateFood.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CateFood.onHoverState.BorderRadius = 25;
            this.CateFood.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateFood.onHoverState.BorderThickness = 1;
            this.CateFood.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CateFood.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CateFood.onHoverState.IconLeftImage = null;
            this.CateFood.onHoverState.IconRightImage = null;
            this.CateFood.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.CateFood.OnIdleState.BorderRadius = 25;
            this.CateFood.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateFood.OnIdleState.BorderThickness = 1;
            this.CateFood.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.CateFood.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.CateFood.OnIdleState.IconLeftImage = null;
            this.CateFood.OnIdleState.IconRightImage = null;
            this.CateFood.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CateFood.OnPressedState.BorderRadius = 25;
            this.CateFood.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateFood.OnPressedState.BorderThickness = 1;
            this.CateFood.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CateFood.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CateFood.OnPressedState.IconLeftImage = null;
            this.CateFood.OnPressedState.IconRightImage = null;
            this.CateFood.Size = new System.Drawing.Size(139, 44);
            this.CateFood.TabIndex = 0;
            this.CateFood.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CateFood.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CateFood.TextMarginLeft = 0;
            this.CateFood.TextPadding = new System.Windows.Forms.Padding(0);
            this.CateFood.UseDefaultRadiusAndThickness = true;
            this.CateFood.Click += new System.EventHandler(this.CateFood_Click);
            // 
            // CateSmoothie
            // 
            this.CateSmoothie.AllowAnimations = true;
            this.CateSmoothie.AllowMouseEffects = true;
            this.CateSmoothie.AllowToggling = false;
            this.CateSmoothie.AnimationSpeed = 200;
            this.CateSmoothie.AutoGenerateColors = false;
            this.CateSmoothie.AutoRoundBorders = false;
            this.CateSmoothie.AutoSizeLeftIcon = true;
            this.CateSmoothie.AutoSizeRightIcon = true;
            this.CateSmoothie.BackColor = System.Drawing.Color.Transparent;
            this.CateSmoothie.BackColor1 = System.Drawing.SystemColors.Control;
            this.CateSmoothie.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("CateSmoothie.BackgroundImage")));
            this.CateSmoothie.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateSmoothie.ButtonText = "SMOOTHIES";
            this.CateSmoothie.ButtonTextMarginLeft = 0;
            this.CateSmoothie.ColorContrastOnClick = 45;
            this.CateSmoothie.ColorContrastOnHover = 45;
            this.CateSmoothie.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.CateSmoothie.CustomizableEdges = borderEdges7;
            this.CateSmoothie.DialogResult = System.Windows.Forms.DialogResult.None;
            this.CateSmoothie.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CateSmoothie.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CateSmoothie.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CateSmoothie.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.CateSmoothie.Font = new System.Drawing.Font("Kantumruy Pro", 10.8F, System.Drawing.FontStyle.Bold);
            this.CateSmoothie.ForeColor = System.Drawing.Color.Black;
            this.CateSmoothie.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.CateSmoothie.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.CateSmoothie.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.CateSmoothie.IconMarginLeft = 11;
            this.CateSmoothie.IconPadding = 10;
            this.CateSmoothie.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.CateSmoothie.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.CateSmoothie.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.CateSmoothie.IconSize = 25;
            this.CateSmoothie.IdleBorderColor = System.Drawing.Color.DimGray;
            this.CateSmoothie.IdleBorderRadius = 25;
            this.CateSmoothie.IdleBorderThickness = 1;
            this.CateSmoothie.IdleFillColor = System.Drawing.SystemColors.Control;
            this.CateSmoothie.IdleIconLeftImage = null;
            this.CateSmoothie.IdleIconRightImage = null;
            this.CateSmoothie.IndicateFocus = false;
            this.CateSmoothie.Location = new System.Drawing.Point(596, 93);
            this.CateSmoothie.Name = "CateSmoothie";
            this.CateSmoothie.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.CateSmoothie.OnDisabledState.BorderRadius = 25;
            this.CateSmoothie.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateSmoothie.OnDisabledState.BorderThickness = 1;
            this.CateSmoothie.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.CateSmoothie.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.CateSmoothie.OnDisabledState.IconLeftImage = null;
            this.CateSmoothie.OnDisabledState.IconRightImage = null;
            this.CateSmoothie.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CateSmoothie.onHoverState.BorderRadius = 25;
            this.CateSmoothie.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateSmoothie.onHoverState.BorderThickness = 1;
            this.CateSmoothie.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.CateSmoothie.onHoverState.ForeColor = System.Drawing.Color.White;
            this.CateSmoothie.onHoverState.IconLeftImage = null;
            this.CateSmoothie.onHoverState.IconRightImage = null;
            this.CateSmoothie.OnIdleState.BorderColor = System.Drawing.Color.DimGray;
            this.CateSmoothie.OnIdleState.BorderRadius = 25;
            this.CateSmoothie.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateSmoothie.OnIdleState.BorderThickness = 1;
            this.CateSmoothie.OnIdleState.FillColor = System.Drawing.SystemColors.Control;
            this.CateSmoothie.OnIdleState.ForeColor = System.Drawing.Color.Black;
            this.CateSmoothie.OnIdleState.IconLeftImage = null;
            this.CateSmoothie.OnIdleState.IconRightImage = null;
            this.CateSmoothie.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CateSmoothie.OnPressedState.BorderRadius = 25;
            this.CateSmoothie.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.CateSmoothie.OnPressedState.BorderThickness = 1;
            this.CateSmoothie.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.CateSmoothie.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.CateSmoothie.OnPressedState.IconLeftImage = null;
            this.CateSmoothie.OnPressedState.IconRightImage = null;
            this.CateSmoothie.Size = new System.Drawing.Size(118, 44);
            this.CateSmoothie.TabIndex = 0;
            this.CateSmoothie.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.CateSmoothie.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.CateSmoothie.TextMarginLeft = 0;
            this.CateSmoothie.TextPadding = new System.Windows.Forms.Padding(0);
            this.CateSmoothie.UseDefaultRadiusAndThickness = true;
            this.CateSmoothie.Click += new System.EventHandler(this.CateSmoothie_Click);
            // 
            // POSForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1483, 805);
            this.Controls.Add(this.bunifuShadowPanel2);
            this.Controls.Add(this.flowLayoutPanelProducts);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.Font = new System.Drawing.Font("Times New Roman", 7.8F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "POSForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "POS";
            this.WindowState = System.Windows.Forms.FormWindowState.Maximized;
            this.Load += new System.EventHandler(this.POSForm_Load);
            ((System.ComponentModel.ISupportInitialize)(this.DgvCheckout)).EndInit();
            this.bunifuShadowPanel2.ResumeLayout(false);
            this.bunifuShadowPanel2.PerformLayout();
            this.bunifuGradientPanel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.BtnClose)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.Btnback)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnAllmenu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCoffee;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CateKhDrink;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CateSmoothie;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanelProducts;
        private Bunifu.UI.WinForms.BunifuDataGridView DgvCheckout;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private System.Windows.Forms.Label lblGrandTotal;
        private System.Windows.Forms.Label lblGrand;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton BtnCheckout;
        private System.Drawing.Printing.PrintDocument printDocument1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton CateFood;
        private Bunifu.UI.WinForms.BunifuTextBox POSSearch;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel2;
        private Bunifu.UI.WinForms.BunifuPictureBox Btnback;
        private Bunifu.UI.WinForms.BunifuPictureBox BtnClose;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Catejuice;
        //private Cafe.ItemControl itemControl1;
        //private Cafe.ItemControl itemControl1;
    }
}